# Generated by Django 2.2.26 on 2022-03-11 10:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=128)),
                ('likes', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='backend')),
                ('original', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_requests_created', to='feed.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_post', to='feed.Post')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_by_user', to='feed.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FollowsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followsuser_by_user', to='feed.UserProfile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followsuser_to_follow', to='feed.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FollowsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followscategory_by_user', to='feed.UserProfile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followscategory_to_follow', to='feed.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=256)),
                ('likes', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_post', to='feed.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by_user', to='feed.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Categorises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorises_in_category', to='feed.Category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorises_post', to='feed.Post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('liker', 'liked_post'), name='Likes'),
        ),
        migrations.AddConstraint(
            model_name='followsuser',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='Follow_user'),
        ),
        migrations.AddConstraint(
            model_name='followscategory',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='Follows_category'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('id', 'post_id', 'user_id'), name='Comment'),
        ),
        migrations.AddConstraint(
            model_name='categorises',
            constraint=models.UniqueConstraint(fields=('post', 'category'), name='Categorises'),
        ),
    ]
