# Generated by Django 2.2.26 on 2022-03-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='categorises',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorises_in_category', to='feed.Category'),
        ),
        migrations.AlterField(
            model_name='categorises',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorises_post', to='feed.Post'),
        ),
        migrations.AlterField(
            model_name='followscategory',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followscategory_by_user', to='feed.UserProfile'),
        ),
        migrations.AlterField(
            model_name='followscategory',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followscategory_to_follow', to='feed.Category'),
        ),
        migrations.AlterField(
            model_name='followsuser',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followsuser_by_user', to='feed.UserProfile'),
        ),
        migrations.AlterField(
            model_name='followsuser',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followsuser_to_follow', to='feed.UserProfile'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_post', to='feed.Post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_by_user', to='feed.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_requests_created', to='feed.UserProfile'),
        ),
    ]
