# Generated by Django 2.2.26 on 2022-03-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorises',
            name='category',
            field=models.ForeignKey(on_delete='cascade', related_name='categorises_in_category', to='feed.Category'),
        ),
    ]
