# Generated by Django 2.2.26 on 2022-03-18 14:34

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20220318_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='original',
            field=models.IntegerField(default=-1, validators=[feed.models.Validators.validate_origin_post]),
        ),
    ]
